accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import sign_up_form

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", sign_up_form, name="signup"),
]

projects/urls.py
from django.urls import path
from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import TaskCreateView, TaskListView, TaskUpdateView

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField("auth.User", related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
# from projects.models import Project
from django.db import models

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        "auth.User", null=True, related_name="tasks", on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm


# Create your views here.


def sign_up_form(request):

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from projects.models import Project
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

# Create your views here.
class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def get_success_url(self):
        return reverse("show_project", args=[self.object.id])

tasks/views.py
from tasks.models import Task
from django.views.generic import CreateView, ListView, UpdateView
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_success_url(self):
        return reverse("show_project", args=[self.object.project.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "tasks/list.html"
    fields = ["is_completed"]

    def get_success_url(self):
        return reverse("show_my_tasks")

projects/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>

        <title></title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_my_tasks' %}"> My Tasks </a>
                        </li>

                        <li>
                            <a href="{% url 'list_projects' %}"> My Projects </a>
                        </li>

                        <li>
                            <a href="{% url 'logout' %}"> Logout </a>
                        </li>

                    {% else %}

                        <li>
                            <a href="{% url 'login' %}"> Login </a>
                        </li>

                        <li>
                            <a href="{% url 'signup' %}"> Signup </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>

        {% block content %}
        {% endblock content %}

        <footer>

        </footer>
    </body>
</html>

projects/templates/projects/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>
                Create a new project
            </h1>
            <form method = "post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>
                    Create
                </button>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
    <main>
        <div>
            <h1>{{ project.name }}</h1>
            <p> {{ project.description|markdownify }}</p>


            <h2> Tasks </h2>
            <p>
                <a href = "{% url 'create_task' %}"> Create a task</a>
            </p>

            <table>
                <thead>
                    <th> Name </th>

                    <th> Assignee </th>

                    <th> Start date </th>

                    <th> Due date </th>

                    <th> Is completed </th>

                    <tbody>
                        {% for task in project.tasks.all %}

                            <tr>

                                <td> {{ task.name }}</td>

                                <td> {{ task.assignee }} </td>

                                <td>{{ task.start_date }}</td>

                                <td> {{ task.due_date }}</td>

                                <td>{{ task.is_completed }}</td>

                            </tr>

                        {% empty %}
                            <p>"This project has no tasks"</p>
                        {% endfor %}
                    </tbody>
                </thread>
            </table>

        </div>
    </main>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>My Projects</h1>
            <p>
                <a href = "{% url 'create_project'%}"> Create a new project</a>
            </p>
            <table>
                {% for project in project_list %}
                    <thead>
                        <th> Name </th>
                        <th> Number of tasks </th>
                        <tbody>

                            <tr>

                                <td>
                                    <a href="{% url 'show_project' project.id %}">{{ project.name }}
                                </td>

                                <td>
                                    {{project.tasks.all|length}}
                                </td>

                            </tr>

                        </tbody>
                    </thead>
                {% empty %}
                    <p>You are not assigned to any projects</p>
                {% endfor %}
            </table>

        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>
                Create a new task
            </h1>
            <form method = "post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>
                    Create
                </button>
            </form>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1> My Tasks </h1>
            <p>
                <a href = "{% url 'create_project'%}"> Create a new project</a>
            </p>

            {% for task in task_list %}
                <table>
                    <thead>
                        <th> Name </th>
                        <th> Start date </th>
                        <th> Due date </th>
                        <th> Is completed </th>
                        <tbody>


                            <tr>
                                <td> {{ task.name }} </td>
                                <td> {{ task.start_date }} </td>
                                <td> {{ task.due_date }} </td>
                                <td> {{ task.is_completed }} </td>


                                {% if task.is_completed == False %}
                                    <form method="post" action="{% url 'complete_task' task.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="is_completed" value="True">
                                        <button>Complete</button>
                                    </form>
                                {% else %}
                                    Done
                                {% endif %}


                            </tr>

                        </tbody>
                    </thead>
                </table>
            {% empty %}
                <p>You have no tasks</p>

            {% endfor %}
        </div>
    </main>

{% endblock content %}